services:
  app:
    image: currency_converter
    build:
      context: .
    container_name: currency_converter_app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5444/currency
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_USERNAME=postgres
    ports:
      - 8080:8080

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=currency
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    ports:
      - 5444:5432

volumes:
  postgres-data: {}
