#GET http://localhost:8080/user

#POST http://localhost:8080/user/registration

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "name": "Tom",
  "surname": "Smith",
  "username": "tom1",
  "password": "Test123$",
  "email": "tom@mail.ru",
  "birthdayDate": "12-12-2000",
  "country": "Belarus"

}