spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/currency
    username: postgres
    password: root

  banner:
    location: classpath:/src/main/resources/banner.txt

  thymeleaf:
    prefix:
      classpath:
        templates:
          suffix: .html
          prefix: classpath:/templates/



